// <auto-generated />
using System;
using EPM.EFCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EPM.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210826061420_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("EPM.Model.DbModel.Department", b =>
                {
                    b.Property<int>("ClusterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUser")
                        .HasColumnType("longtext");

                    b.Property<string>("Dep")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ID")
                        .HasColumnType("char(36)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ParentID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("longtext");

                    b.HasKey("ClusterID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EPM.Model.DbModel.Menu", b =>
                {
                    b.Property<int>("ClusterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUser")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ID")
                        .HasColumnType("char(36)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("ParentList")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ParentMenuID")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("ClusterID");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("EPM.Model.DbModel.Role", b =>
                {
                    b.Property<int>("ClusterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUser")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("HalfCheckeds")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ID")
                        .HasColumnType("char(36)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("longtext");

                    b.HasKey("ClusterID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ClusterID = 1,
                            CreateTime = new DateTime(2021, 8, 26, 14, 14, 19, 682, DateTimeKind.Local).AddTicks(7660),
                            CreateUser = "系统管理员",
                            ID = new Guid("d10f7e9f-d075-443d-bcd3-ef6f64903d92"),
                            IsDeleted = 0,
                            Name = "系统管理员",
                            UpdateTime = new DateTime(2021, 8, 26, 14, 14, 19, 682, DateTimeKind.Local).AddTicks(8523),
                            UpdateUser = "系统管理员"
                        });
                });

            modelBuilder.Entity("EPM.Model.DbModel.RoleMenu", b =>
                {
                    b.Property<int>("ClusterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUser")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ID")
                        .HasColumnType("char(36)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<Guid>("MenuID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("longtext");

                    b.HasKey("ClusterID");

                    b.ToTable("RoleMenus");
                });

            modelBuilder.Entity("EPM.Model.DbModel.User", b =>
                {
                    b.Property<int>("ClusterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUser")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DepartmentID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ID")
                        .HasColumnType("char(36)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<int>("LoginErrorCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LoginLockTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LoginName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LoginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PasswordUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Position")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("longtext");

                    b.HasKey("ClusterID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ClusterID = 1,
                            CreateTime = new DateTime(2021, 8, 26, 14, 14, 19, 686, DateTimeKind.Local).AddTicks(4692),
                            CreateUser = "系统管理员",
                            DepartmentID = new Guid("7946dffb-209c-4d3d-88ed-df25c4eec325"),
                            ID = new Guid("44f2fbfc-6832-4157-b8c2-e9f7da3b6a65"),
                            IsDeleted = 0,
                            LoginErrorCount = 0,
                            LoginName = "admin",
                            Name = "系统管理员",
                            Password = "e10adc3949ba59abbe56e057f20f883e",
                            RoleID = new Guid("d10f7e9f-d075-443d-bcd3-ef6f64903d92"),
                            Status = 0,
                            UpdateTime = new DateTime(2021, 8, 26, 14, 14, 19, 686, DateTimeKind.Local).AddTicks(4693),
                            UpdateUser = "系统管理员"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
